# ----------------------------------------
# Created on: Mon Nov 15 11:23:53 2021
# Auto generated by Pango
# ----------------------------------------

vsim  -voptargs="+acc" -L work soc_tb
add wave *
view wave
view structure
view signals

run 

# ----------------------------------------
