# ----------------------------------------
# Created on: Mon Nov 15 11:23:53 2021
# Auto generated by Pango
# ----------------------------------------

vlib  work
vmap  work ./work
vlog   "C:/Users/Misaka/Desktop/riscv_final/risc-v/source/soc/defines.v" -work work
vlog   "C:/Users/Misaka/Desktop/riscv_final/risc-v/source/rtl/OLED_drive.v" -work work
vlog   "C:/Users/Misaka/Desktop/riscv_final/risc-v/source/perips/gpio.v" -work work
vlog   "C:/Users/Misaka/Desktop/riscv_final/risc-v/source/utils/defines.v" -work work
vlog   "C:/Users/Misaka/Desktop/riscv_final/risc-v/source/uart/uart_rx.v" -work work
vlog   "C:/Users/Misaka/Desktop/riscv_final/risc-v/source/perips/rom.v" -work work
vlog   "C:/Users/Misaka/Desktop/riscv_final/risc-v/source/perips/timer.v" -work work
vlog   "C:/Users/Misaka/Desktop/riscv_final/risc-v/source/core/riscv.v" -work work
vlog   "C:/Users/Misaka/Desktop/riscv_final/risc-v/source/source/defines.v" -work work
vlog   "C:/Users/Misaka/Desktop/riscv_final/risc-v/source/soc/riscv_soc_top.v" -work work
vlog   "C:/Users/Misaka/Desktop/riscv_final/risc-v/source/rtl/data_conv.v" -work work
vlog   "C:/Users/Misaka/Desktop/riscv_final/risc-v/source/core/fetch2reg.v" -work work
vlog   "C:/Users/Misaka/Desktop/riscv_final/risc-v/source/utils/full_handshake_rx.v" -work work
vlog   "C:/Users/Misaka/Desktop/riscv_final/risc-v/source/core/Control.v" -work work
vlog   "C:/Users/Misaka/Desktop/riscv_final/risc-v/source/rtl/DHT22_driver.v" -work work
vlog   "C:/Users/Misaka/Desktop/riscv_final/risc-v/source/utils/gen_buf.v" -work work
vlog   "C:/Users/Misaka/Desktop/riscv_final/risc-v/source/debug/jtag_top.v" -work work
vlog   "C:/Users/Misaka/Desktop/riscv_final/risc-v/source/rtl/top_module.v" -work work
vlog   "C:/Users/Misaka/Desktop/riscv_final/risc-v/source/perips/pwm.v" -work work
vlog   "C:/Users/Misaka/Desktop/riscv_final/risc-v/source/Desktop/defines.v" -work work
vlog   "C:/Users/Misaka/Desktop/riscv_final/risc-v/source/utils/full_handshake_tx.v" -work work
vlog   "C:/Users/Misaka/Desktop/riscv_final/risc-v/source/rtl/bcd_8421.v" -work work
vlog   "C:/Users/Misaka/Desktop/riscv_final/risc-v/source/debug/defines.v" -work work
vlog   "C:/Users/Misaka/Desktop/riscv_final/risc-v/source/rtl/HEX8.v" -work work
vlog   "C:/Users/Misaka/Desktop/riscv_final/risc-v/source/rtl/uart_tx.v" -work work
vlog   "C:/Users/Misaka/Desktop/riscv_final/risc-v/source/uart/defines.v" -work work
vlog   "C:/Users/Misaka/Desktop/riscv_final/risc-v/source/core/recognition.v" -work work
vlog   "C:/Users/Misaka/Desktop/riscv_final/risc-v/source/core/defines.v" -work work
vlog   "C:/Users/Misaka/Desktop/riscv_final/risc-v/source/uart/uart_tx.v" -work work
vlog   "C:/Users/Misaka/Desktop/riscv_final/risc-v/source/core/csr_reg.v" -work work
vlog   "C:/Users/Misaka/Desktop/riscv_final/risc-v/source/perips/spi.v" -work work
vlog   "C:/Users/Misaka/Desktop/riscv_final/risc-v/source/debug/jtag_driver.v" -work work
vlog   "C:/Users/Misaka/Desktop/riscv_final/risc-v/source/debug/jtag_dm.v" -work work
vlog   "C:/Users/Misaka/Desktop/riscv_final/risc-v/source/core/regs.v" -work work
vlog   "C:/Users/Misaka/Desktop/riscv_final/risc-v/source/rtl/defines.v" -work work
vlog   "C:/Users/Misaka/Desktop/riscv_final/risc-v/source/perips/uart.v" -work work
vlog   "C:/Users/Misaka/Desktop/riscv_final/risc-v/source/utils/gen_dff.v" -work work
vlog   "C:/Users/Misaka/Desktop/riscv_final/risc-v/source/core/interruptor.v" -work work
vlog   "C:/Users/Misaka/Desktop/riscv_final/risc-v/source/perips/ram.v" -work work
vlog   "C:/Users/Misaka/Desktop/riscv_final/risc-v/source/core/rvbus.v" -work work
vlog   "C:/Users/Misaka/Desktop/riscv_final/risc-v/source/core/division.v" -work work
vlog   "C:/Users/Misaka/Desktop/riscv_final/risc-v/source/core/recognition2reg.v" -work work
vlog   "C:/Users/Misaka/Desktop/riscv_final/risc-v/source/core/fetch.v" -work work
vlog   "C:/Users/Misaka/Desktop/riscv_final/risc-v/source/perips/defines.v" -work work
vlog   "C:/Users/Misaka/Desktop/riscv_final/risc-v/source/debug/uart_debug.v" -work work
vlog   "C:/Users/Misaka/Desktop/riscv_final/risc-v/source/core/execute.v" -work work
vlog   "C:/Users/Misaka/Desktop/riscv_final/risc-v/source/uart/hc05_top.v" -work work
vlog   "C:/Users/Misaka/Desktop/riscv_final/risc-v/source/Desktop/key_filter.v" -work work
vlog   "C:/Users/Misaka/Desktop/riscv_final/risc-v/source/my_riscv_soc_sim_11.11/source/soc_tb.v" -work work

# ----------------------------------------
